spring:
  datasource:
    hikari:
      batch:
        jdbc-url: jdbc:mysql://hostname:3306/batch
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: password
      demo:
        jdbc-url: jdbc:mysql://hostname:3306/demo?rewriteBatchedStatements=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: password
  batch:
    initialize-schema: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
logging:
  level:
    root: info