spring:
  datasource:
    hikari:
      batch:
        jdbc-url: jdbc:mysql://host/batch
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: wlffjt1akf
      demo:
        jdbc-url: jdbc:mysql://host/demo
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: name
        password: pw
  batch:
    initialize-schema: always
    job:
      names: ${job.names:createBoardJob}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
logging:
  level:
    root: info